### ISSUE TITLE
Trying to connect over SSL causes IOException:  Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by canton7** [IrcDotNet/IrcDotNet#49]
To reproduce:

1. Fresh clone of the repository, open the sln
2. Open IrcBot.cs, change line 159 to `client.Connect(server, true, registrationInfo);` (to enable ssl).
3. Start the "MarkovTextBot" sample
4. When prompted, enter "connect chat.freenode.net" (which listens on port 6667 for SSL connections)

The following exception is thrown:

```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at IrcDotNet.StandardIrcClient.GetDataStream(Boolean useSsl, String targetHost) in C:\Documents\projects\IrcDotNet\source\IrcDotNet\StandardIrcClient.cs:line 592
   at IrcDotNet.StandardIrcClient.ConnectCompleted(Object sender, SocketAsyncEventArgs e) in C:\Documents\projects\IrcDotNet\source\IrcDotNet\StandardIrcClient.cs:line 444
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

Inner Exception 1:
IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
```

Where the InnerException is:

```
System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   at System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

I tried the same with another IRC server (also over SSL), with the same result.

**Comment by canton7** [comment]
The issue is that CircularBufferStream.Read returns 0 when there is not yet any available data. SslStream expects Stream.Read to block until there is available data. I'm not sure that there's any way to make it block without making CircularBufferStream thread-safe.

**Comment by wledfor2** [comment]
Anyone have a workaround for this issue in the mean time? It's pretty crippling, with many networks going SSL only.

**Comment by wledfor2** [comment]
Does anyone have a temp workaround for this issue? It's very crippling, with more and more IRC networks going SSL only.

**Comment by paralin** [comment]
I'll have a look at the issue tonight and will release a fix soon.

**Comment by canton7** [comment]
I haven't looked at the code since I last commented, but I suspect the solution is to wrap the SslStream around the NetworkStream, then wrap the CircularBufferStream around the SslStream, rather than SslStream around the CircularBufferStream around the NetworkStream.

**Comment by wledfor2** [comment]
Thanks, both of you. I tried fixing the issue myself for a PR but had no luck.

**Comment by canton7** [comment]
The comments make it look like it was supposed to open the SslStream directly over the NetworkStream: https://github.com/IrcDotNet/IrcDotNet/blob/8151fa8bff2bc031fb3e0b730624c3d678b0c9ff/source/IrcDotNet/StandardIrcClient.cs#L439. I suspect someone broke something at some point when the CircularBufferStream was introduced.

**Comment by hypodyne** [comment]
I get the same issue using SSL and the Standard IRC client. 

Platform Unity/Mono.

**Comment by isaackearl** [comment]
Did anybody ever find a resolution for this?  I still cannot connect SSL/TLS using IrcDotNet using the StandardIrcClient.

**Comment by canton7** [comment]
I abandoned it and moved on. Much like the authors...

**Comment by oreleraki** [comment]
@canton7, Hi, after seeing there are no maintainers, i asked by the Owner and became a Maintainer. I will soon start updating the libraries and my first goals will be fixing crashes. If you will be patient a bit more, i will check this matter and hope to implement a fix soon.

**Comment by isaackearl** [comment]
@oreleraki that is very awesome.  Thanks for jumping in and taking over!

**Comment by BishopofCorinth** [comment]
Also running into this issue. Eagerly awaiting a fix. Thank you for picking up the work!

**Comment by shuyangw** [comment]
Has there been any update on this issue? I've been looking into this myself but haven't gotten anywhere yet.

**Comment by alexandergre** [comment]
I managed to fix the problem for myself by modifying StandardIrcClient to use stream from TcpClient instead of CircularBufferStream for as an underlying stream for SslStream.  The problem is likely to be with CircularBufferStream but I was unable to figure out the way it works (how does data received from socket get into its buffer?)

**Comment by alexandergre** [comment]
I think I managed to fix this, created PR: https://github.com/IrcDotNet/IrcDotNet/pull/87
Testing is welcome

**Comment by kreditor0815** [comment]
is there any progress on this?

**Comment by TheUnstoppable** [comment]
I have a fork of this project in my page, that has a working SSL connection with certificate support.
https://github.com/TheUnstoppable/IrcDotNet
