### ISSUE TITLE
Unhandled exception. System.NotSupportedException: This protocol version is not supported.

### ISSUE THREAD

**Issue by njlr** [IrcDotNet/IrcDotNet#83]
To test out the library I am trying to connect to a server and list the channels. 

However, I get the exception `This protocol version is not supported`:

```
Unhandled exception. System.NotSupportedException: This protocol version is not supported.
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e, Boolean userSocket)
   at System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e)
   at IrcDotNet.StandardIrcClient.ConnectAsync(EndPoint remoteEndPoint, Object token)
   at IrcDotNet.StandardIrcClient.Connect(EndPoint remoteEndPoint, Boolean useSsl, IrcRegistrationInfo registrationInfo)
   at IrcDotNet.StandardIrcClient.Connect(String hostName, Int32 port, Boolean useSsl, IrcRegistrationInfo registrationInfo)
...
```

```csharp
var irc = new StandardIrcClient ()

var host = "chat.freenode.net"
var port = 6667

var regInfo = IrcUserRegistrationInfo ()
r.UserName = "testaccount123"
r.NickName = "testaccount1234"
r.RealName = "testaccount12345"

irc.Connect (host, port, true, regInfo)
```

Have I somehow configured this incorrectly or is this a limitation of the library?

Note: I am able to connect to the server using HexChat.

**Comment by canton7** [comment]
Duplicate of #49?

**Comment by alexandergre** [comment]
I think I managed to fix this, created PR: https://github.com/IrcDotNet/IrcDotNet/pull/87
Testing is welcome
