### ISSUE TITLE
System.ArgumentException: collection contains an invalid Channelname

### ISSUE THREAD

**Issue by Sonic3R** [IrcDotNet/IrcDotNet#86]
Hi

I have channel name like `#my.channel.for.you` and when trying to join it, I give exception:

```
System.ArgumentException: collection contains an invalid Channelname ( #my.channel.for.you)!
   at IrcDotNet.IrcClient.EnsureChannelName(String c)
   at IrcDotNet.IrcClient.<SendMessageJoin>b__350_0(String c)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IrcDotNet.IrcClient.SendMessageJoin(IEnumerable`1 channels)
   at IrcSystem.Core.IrcManager.<>c__DisplayClass14_0.<<Build>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

The code is:

```
var client = new StandardIrcClient();
IrcUserRegistrationInfo info = new IrcUserRegistrationInfo
      {
        NickName = _nick,
        Password = _password,
        RealName = _nick,
        UserName = _nick
      };

client.Registered += async (s, ev) =>
{
   client.Channels.Join("#my.channel.for.you"); // here is line where exception is thrown
}
```

What is the fix ?

**Comment by Sonic3R** [comment]
Was my fault, the channel name contained a space which I didn't see. No issue.
